Fix default value for heatmap
Error: Missing required argument

  on sfx_shared_prd.tf line 325, in resource "signalfx_heatmap_chart" "sfx_ES11iOhAAAA":
 325:   color_range {

The argument "color" is required, but no definition was found.